### PR TITLE
NSIS 3.09 to 3.10

### PR DESCRIPTION
**Pull request by dpy013**
[Release Notes](http://nsis.sourceforge.net/Docs/AppendixF.html#v3.10)

### CODE REVIEW

**Comment by seanbudd** [comment]
Please update the version listed in the read me

**Comment by seanbudd** [comment]
@dpy013 - have you tested this in NVDA yet with a build?

I've confirmed that the files changed look fine

**Comment by dpy013** [comment]
Only the portable version of NVDA was created and tested for operation.

**Comment by seanbudd** [comment]
Can you update the version listed in this projects README still?

**Pull request merged**
